# 서울시 인구 데이터 분석

In [9]:
!pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.5/96.5 kB 5.0 MB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

In [12]:
# 라이브러리 import
import os
import numpy as np
import pandas as pd
import folium
import seaborn as sns
import matplotlib.pyplot as plt

In [46]:
# 데이터 파일 read
seoul_file = pd.read_excel("./xlsx etc/seoul_popular_data.xls", header=2, usecols="B,D,G,J,N")

In [49]:

# 컬럼명 변경:
# 자치구 -> 구, 합계 -> 인구수, 등록외국인 - > 외국인, 65세이상고령자 -> 고령자
seoul_file.columns
seoul_file.columns=["구","인구수","한국인","외국인","고령자"]

In [52]:
# 함계행 제거
seoul_file.drop([0],inplace=True)

KeyError: '[0] not found in axis'

In [58]:
new_seoul_file = seoul_file.reset_index()
new_seoul_file

    index     구     인구수     한국인    외국인    고령자
0       1   종로구  153684  144275   9409  28064
1       2    중구  131450  122173   9277  24742
2       3   용산구  236518  222169  14349  39461
3       4   성동구  291609  285073   6536  46896
4       5   광진구  353110  340707  12403  52604
5       6  동대문구  352592  337982  14610  62963
6       7   중랑구  393600  389043   4557  72851
7       8   성북구  442680  433150   9530  75719
8       9   강북구  300824  297384   3440  64961
9      10   도봉구  318100  316098   2002  65122
10     11   노원구  514445  510486   3959  89426
11     12   은평구  476013  472259   3754  88418
12     13  서대문구  317075  305866  11209  55012
13     14   마포구  378629  368331  10298  55168
14     15   양천구  449378  446182   3196  69953
15     16   강서구  578426  573046   5380  93924
16     17   구로구  419984  396017  23967  73864
17     18   금천구  244901  231098  13803  41819
18     19  영등포구  400241  376740  23501  63547
19     20   동작구  394649  386017   8632  67470
20     21   관악구  500336  486375  13961  80686
21     22   서초구  413677  409823   3854  61404
22     23   강남구  537338  532577   4761  79575
23     24   송파구  668261  662607   5654  99854
24     25   강동구  465097  461300   3797  75477

In [59]:
new_seoul_file.drop('index',inplace=True,axis=1)
new_seoul_file

       구     인구수     한국인    외국인    고령자
0    종로구  153684  144275   9409  28064
1     중구  131450  122173   9277  24742
2    용산구  236518  222169  14349  39461
3    성동구  291609  285073   6536  46896
4    광진구  353110  340707  12403  52604
5   동대문구  352592  337982  14610  62963
6    중랑구  393600  389043   4557  72851
7    성북구  442680  433150   9530  75719
8    강북구  300824  297384   3440  64961
9    도봉구  318100  316098   2002  65122
10   노원구  514445  510486   3959  89426
11   은평구  476013  472259   3754  88418
12  서대문구  317075  305866  11209  55012
13   마포구  378629  368331  10298  55168
14   양천구  449378  446182   3196  69953
15   강서구  578426  573046   5380  93924
16   구로구  419984  396017  23967  73864
17   금천구  244901  231098  13803  41819
18  영등포구  400241  376740  23501  63547
19   동작구  394649  386017   8632  67470
20   관악구  500336  486375  13961  80686
21   서초구  413677  409823   3854  61404
22   강남구  537338  532577   4761  79575
23   송파구  668261  662607   5654  99854
24   강동구  465097  461300   3797  75477

In [88]:
## (4) 각 구별 전체 인구를 이용해서 구별 "외국인비율"과 "고령자비율"을 추가하고, 소수점 첫째자리 반올림하기
### - 외국인 비율: 외국인/인구수 * 100
### - 고령자 비율: 고령자 / 인구수 * 100

new_seoul_file["인구수"]= new_seoul_file["인구수"].astype("int")
new_seoul_file["한국인"] = new_seoul_file["한국인"].astype("int")
new_seoul_file["외국인"] = new_seoul_file["외국인"].astype("int")
new_seoul_file["고령자"] = new_seoul_file["고령자"].astype("int")


new_seoul_file["외국인비율"] = round((new_seoul_file["외국인"]/new_seoul_file["인구수"])*100, 1)
new_seoul_file["고령자비율"] = round((new_seoul_file["고령자"]/new_seoul_file["인구수"])*100, 1)

new_seoul_file

       구     인구수     한국인    외국인    고령자  외국인비율  고령자비율
0    종로구  153684  144275   9409  28064    6.1   18.3
1     중구  131450  122173   9277  24742    7.1   18.8
2    용산구  236518  222169  14349  39461    6.1   16.7
3    성동구  291609  285073   6536  46896    2.2   16.1
4    광진구  353110  340707  12403  52604    3.5   14.9
5   동대문구  352592  337982  14610  62963    4.1   17.9
6    중랑구  393600  389043   4557  72851    1.2   18.5
7    성북구  442680  433150   9530  75719    2.2   17.1
8    강북구  300824  297384   3440  64961    1.1   21.6
9    도봉구  318100  316098   2002  65122    0.6   20.5
10   노원구  514445  510486   3959  89426    0.8   17.4
11   은평구  476013  472259   3754  88418    0.8   18.6
12  서대문구  317075  305866  11209  55012    3.5   17.3
13   마포구  378629  368331  10298  55168    2.7   14.6
14   양천구  449378  446182   3196  69953    0.7   15.6
15   강서구  578426  573046   5380  93924    0.9   16.2
16   구로구  419984  396017  23967  73864    5.7   17.6
17   금천구  244901  231098  13803  41819    5.6   17.1
18  영등포구  400241  376740  23501  63547    5.9   15.9
19   동작구  394649  386017   8632  67470    2.2   17.1
20   관악구  500336  486375  13961  80686    2.8   16.1
21   서초구  413677  409823   3854  61404    0.9   14.8
22   강남구  537338  532577   4761  79575    0.9   14.8
23   송파구  668261  662607   5654  99854    0.8   14.9
24   강동구  465097  461300   3797  75477    0.8   16.2

In [89]:
# (5) 인구수별로 내림차순 정렬(sort)하기
new_seoul_file.sort_values(by="인구수", ascending=False)

       구     인구수     한국인    외국인    고령자  외국인비율  고령자비율
23   송파구  668261  662607   5654  99854    0.8   14.9
15   강서구  578426  573046   5380  93924    0.9   16.2
22   강남구  537338  532577   4761  79575    0.9   14.8
10   노원구  514445  510486   3959  89426    0.8   17.4
20   관악구  500336  486375  13961  80686    2.8   16.1
11   은평구  476013  472259   3754  88418    0.8   18.6
24   강동구  465097  461300   3797  75477    0.8   16.2
14   양천구  449378  446182   3196  69953    0.7   15.6
7    성북구  442680  433150   9530  75719    2.2   17.1
16   구로구  419984  396017  23967  73864    5.7   17.6
21   서초구  413677  409823   3854  61404    0.9   14.8
18  영등포구  400241  376740  23501  63547    5.9   15.9
19   동작구  394649  386017   8632  67470    2.2   17.1
6    중랑구  393600  389043   4557  72851    1.2   18.5
13   마포구  378629  368331  10298  55168    2.7   14.6
4    광진구  353110  340707  12403  52604    3.5   14.9
5   동대문구  352592  337982  14610  62963    4.1   17.9
9    도봉구  318100  316098   2002  65122    0.6   20.5
12  서대문구  317075  305866  11209  55012    3.5   17.3
8    강북구  300824  297384   3440  64961    1.1   21.6
3    성동구  291609  285073   6536  46896    2.2   16.1
17   금천구  244901  231098  13803  41819    5.6   17.1
2    용산구  236518  222169  14349  39461    6.1   16.7
0    종로구  153684  144275   9409  28064    6.1   18.3
1     중구  131450  122173   9277  24742    7.1   18.8

In [ ]:
# (6) 외국인, 외국인비율로 내림차순 정렬하기

In [ ]:
# (7) 고령자수 / 고령자비율로 내림차순 정렬하기

In [90]:
# (8) 인데스 값을 '구'별 데이터로 변경하기